image: ubuntu:18.04
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y curl llvm-dev libclang-dev clang git cmake pkg-config libunwind-dev golang
          - git submodule update --init --recursive
          - curl -Lq https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 | tar xjf - -C ~
          - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s - '-y' --default-toolchain=nightly-2019-09-28
          - source $HOME/.cargo/env
          - cargo install bindgen
          - rustup target add thumbv8m.main-none-eabi
          - export PATH=$PATH:~/gcc-arm-none-eabi-8-2018-q4-major/bin
          - export NEWLIB_PATH=~/gcc-arm-none-eabi-8-2018-q4-major/arm-none-eabi/include
          - bash ./release.sh
          - cargo test -v
